name: ci-master-pr

on:
  push:
    branches:
    - master
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: bats/bats:1.11.0
    steps:
    - uses: actions/checkout@v4
    - name: Install git
      run: |
        apk add --no-cache git
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"
    - name: Test
      run: |
        bats ./gen-changelog.bats
